template:
  - sensor:
      - name: "Garage Door"
        state: >
          {% if is_state('binary_sensor.garage_sensor', 'on') and is_state('switch.garage_door', 'on') %}
            opening
          {% elif is_state('binary_sensor.garage_sensor', 'off') and is_state('switch.garage_door', 'on') %}
            closing
          {% elif is_state('binary_sensor.garage_sensor', 'off') %}
            open
          {% elif is_state('binary_sensor.garage_sensor', 'unavailable') %}
            {{ states("sensor.garage_door") }}
          {% else %}
            closed
          {% endif %}

## We need to see statistics of the door.
sensor:
  - platform: history_stats
    name: Garage door Open today
    entity_id: sensor.garage_door
    state: "open"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Garage door Opening times today
    entity_id: sensor.garage_door
    state: "opening"
    type: count
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Garage door Closing times today
    entity_id: sensor.garage_door
    state: "closing"
    type: count
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Garage door Open times today
    entity_id: sensor.garage_door
    state: "open"
    type: count
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Garage door Closed times today
    entity_id: sensor.garage_door
    state: "closed"
    type: count
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Garage door unavailable times today
    entity_id: binary_sensor.garage_sensor
    state: "unavailable"
    type: count
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"
  - platform: history_stats
    name: Garage door unavailable today
    entity_id: binary_sensor.garage_sensor
    state: "unavailable"
    type: time
    start: "{{ now().replace(hour=0, minute=0, second=0) }}"
    end: "{{ now() }}"

cover:
  - platform: template
    covers:
      garage_door:
        device_class: garage
        friendly_name: "Garage Door"
        value_template: "{{ states('sensor.garage_door') }}"
        open_cover:
          - condition: state
            entity_id: sensor.garage_door
            state: "closed"
          - service: switch.toggle
            target:
              entity_id: switch.garage_door
        close_cover:
          - condition: state
            entity_id: sensor.garage_door
            state: "open"
          - service: switch.toggle
            target:
              entity_id: switch.garage_door
        stop_cover:
          service: switch.toggle
          target:
            entity_id: switch.garage_door
        icon_template: >-
          {% if is_state('cover.garage_door', 'opening') or is_state('cover.garage_door', 'closing') %}
            mdi:garage-alert
          {% elif is_state('cover.garage_door', 'open') %}
            mdi:garage-open
          {% elif is_state('cover.garage_door', 'closed') %}
            mdi:garage
          {% endif %}
